# Generated by Django 4.1.3 on 2022-11-29 07:28

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150)),
                ('service_plan', models.TextField()),
                ('url', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('founder_photo', models.ImageField(upload_to=pages.models.image_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
