# Generated by Django 4.1.3 on 2022-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_chapter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(),
        ),
    ]
