# Generated by Django 4.1.3 on 2022-11-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_chapter_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='main_photo',
            new_name='front_photo',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='photo_7',
            new_name='pastor_photo',
        ),
    ]
