# Generated by Django 4.1.3 on 2022-12-01 11:28

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sermon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path),
        ),
    ]
