# Generated by Django 4.1.3 on 2022-12-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_verse_verse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='verse',
            field=models.TextField(),
        ),
    ]
