# Generated by Django 4.1.3 on 2022-12-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_event_location_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='inverted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
