# Generated by Django 4.1.3 on 2022-12-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_event_inverted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='inverted',
            field=models.BooleanField(default=True),
        ),
    ]
