# Generated by Django 4.1.3 on 2022-12-03 11:48

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_event_inverted'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(upload_to=pages.models.image_file_path)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
