# Generated by Django 4.1.3 on 2022-12-03 12:21

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_url_book_purchase_url_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=pages.models.image_file_path),
        ),
    ]
