# Generated by Django 4.1.3 on 2022-12-03 12:43

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to=pages.models.image_file_path)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('books', models.ManyToManyField(related_name='founder_books', to='pages.book')),
            ],
        ),
    ]
