# Generated by Django 4.1.3 on 2022-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_aboutfounder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutfounder',
            options={'verbose_name': 'Founder', 'verbose_name_plural': 'About the Founder'},
        ),
        migrations.AlterField(
            model_name='aboutfounder',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='founder_books', to='pages.book'),
        ),
    ]
