# Generated by Django 4.1.3 on 2022-12-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_book_created_at_alter_book_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutfounder',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutfounder',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutfounder',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='purchase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
