# Generated by Django 4.1.3 on 2022-12-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_aboutfounder_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfounder',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='pages.book'),
        ),
    ]
