# Generated by Django 4.1.3 on 2022-12-04 14:02

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_aboutfounder_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giving_type', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('png', models.ImageField(upload_to=pages.models.image_file_path)),
                ('inverted', models.BooleanField(default=True)),
            ],
        ),
    ]
