# Generated by Django 4.1.3 on 2022-12-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_giving'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giving',
            options={'verbose_name': 'Giving', 'verbose_name_plural': 'Giving'},
        ),
        migrations.AddField(
            model_name='sermon',
            name='interdenominational',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
