# Generated by Django 4.1.3 on 2022-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_giving_options_sermon_interdenominational'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='interdenominational',
            field=models.BooleanField(default=True),
        ),
    ]
