# Generated by Django 4.1.3 on 2022-12-04 14:29

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_sermon_interdenominational'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to=pages.models.image_file_path)),
            ],
        ),
    ]
