# Generated by Django 4.1.3 on 2022-12-04 14:37

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_imageslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageslider',
            options={'verbose_name': 'Landing Page Image'},
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='photo_1',
            field=models.ImageField(upload_to=pages.models.image_file_path),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='photo_2',
            field=models.ImageField(upload_to=pages.models.image_file_path),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='photo_3',
            field=models.ImageField(upload_to=pages.models.image_file_path),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='photo_4',
            field=models.ImageField(upload_to=pages.models.image_file_path),
        ),
    ]
