# Generated by Django 4.1.3 on 2022-12-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_imageslider_options_alter_imageslider_photo_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageslider',
            old_name='batch_id',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='imageslider',
            old_name='photo_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='imageslider',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='imageslider',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='imageslider',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='imageslider',
            name='photo_5',
        ),
    ]
