# Generated by Django 4.1.3 on 2022-12-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_rename_batch_id_imageslider_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslider',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
