# Generated by Django 4.1.3 on 2022-12-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_imageslider_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageslider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imageslider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
