# Generated by Django 4.1.3 on 2022-12-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_belief'),
    ]

    operations = [
        migrations.AddField(
            model_name='belief',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
