# Generated by Django 4.1.3 on 2022-12-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_belief_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belief',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
