# Generated by Django 4.1.3 on 2022-12-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_testimony'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='subject_of_testimony',
        ),
        migrations.AddField(
            model_name='testimony',
            name='testimony_subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
