# Generated by Django 4.1.3 on 2022-12-16 11:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_testimony_testimony_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
