# Generated by Django 4.1.3 on 2022-12-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_alter_testimony_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
