# Generated by Django 4.1.3 on 2022-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_alter_testimony_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='active',
        ),
        migrations.AddField(
            model_name='testimony',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
