# Generated by Django 4.1.3 on 2022-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_remove_testimony_active_testimony_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
