# Generated by Django 4.1.3 on 2022-12-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_alter_testimony_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': 'Testimony', 'verbose_name_plural': 'Testimonies'},
        ),
    ]
