# Generated by Django 4.1.3 on 2022-12-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_alter_testimony_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
